> ### Note on Labs and Assignments:
>
> 🔧 Look for the **wrench emoji** 🔧 — it highlights where you're expected to take action!
>
> These sections are graded and are not optional.
>

# IS 4487 Lab 2

## Outline

- Loading installed packages
- Inspect data
- Filter, sort and aggregate the data

<a href="https://colab.research.google.com/github/Stan-Pugsley/is_4487_base/blob/main/Labs/lab_02_dataframe_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

More information:
- Learn more about Colab here:  https://research.google.com/colaboratory/faq.html
- Learn more about Pandas here: https://pandas.pydata.org/docs/user_guide/10min.html

### Context: Motor Trend Car Road Tests

In this lab, you will work with the mtcars dataset, a classic collection of data about cars from the 1970s. It includes features such as miles per gallon (mpg), horsepower, weight, number of cylinders, and transmission type. Although the dataset is relatively small, it contains enough variety to explore meaningful relationships—like how a car’s weight impacts fuel efficiency or how horsepower relates to performance. Because it is clean, well-structured, and widely used in data science education, mtcars is an excellent starting point for learning Python tools like pandas, data visualization, and basic statistical analysis without the added complexity of messy real-world data.  

The MTCARS data consists of the following variables (columns):

| Column | Description                              |
| ------ | ---------------------------------------- |
| mpg    | Miles per gallon (fuel efficiency)       |
| cyl    | Number of cylinders                      |
| disp   | Displacement (cu. in.)                   |
| hp     | Gross horsepower                         |
| drat   | Rear axle ratio                          |
| wt     | Weight (1000 lbs)                        |
| qsec   | ¼ mile time                              |
| vs     | Engine type (0 = V-shaped, 1 = straight) |
| am     | Transmission (0 = automatic, 1 = manual) |
| gear   | Number of forward gears                  |
| carb   | Number of carburetors                    |


Your task is to import the data into a dataframe and learn to work with it as you would an Excel sheet.


## Load Libraries

In this assignment we will be using
- Pandas

We can pull sample data from
- statsmodels.api

In [1]:
import pandas as pd
import statsmodels.api as sm

## Getting data into Pandas

In this case we will load data from the statsmodels.org library.  The data is built in to a Python library, so we don't need to export it from an external source.  In future labs, we will pull the data from GitHub or other sources.

In [2]:
mtcars = sm.datasets.get_rdataset("mtcars", "datasets", cache=True).data
df = pd.DataFrame(mtcars)
df['carmodel'] = df.index
print(df)

                      mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
rownames
Mazda RX4            21.0    6  160.0  110  3.90  2.620  16.46   0   1     4
Mazda RX4 Wag        21.0    6  160.0  110  3.90  2.875  17.02   0   1     4
Datsun 710           22.8    4  108.0   93  3.85  2.320  18.61   1   1     4
Hornet 4 Drive       21.4    6  258.0  110  3.08  3.215  19.44   1   0     3
Hornet Sportabout    18.7    8  360.0  175  3.15  3.440  17.02   0   0     3
Valiant              18.1    6  225.0  105  2.76  3.460  20.22   1   0     3
Duster 360           14.3    8  360.0  245  3.21  3.570  15.84   0   0     3
Merc 240D            24.4    4  146.7   62  3.69  3.190  20.00   1   0     4
Merc 230             22.8    4  140.8   95  3.92  3.150  22.90   1   0     4
Merc 280             19.2    6  167.6  123  3.92  3.440  18.30   1   0     4
Merc 280C            17.8    6  167.6  123  3.92  3.440  18.90   1   0     4
Merc 450SE           16.4    8  275.8  180  3.07  4.070  17.40   0   0     3
Merc 450SL           17.3    8  275.8  180  3.07  3.730  17.60   0   0     3
Merc 450SLC          15.2    8  275.8  180  3.07  3.780  18.00   0   0     3
Cadillac Fleetwood   10.4    8  472.0  205  2.93  5.250  17.98   0   0     3
Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3
Chrysler Imperial    14.7    8  440.0  230  3.23  5.345  17.42   0   0     3
Fiat 128             32.4    4   78.7   66  4.08  2.200  19.47   1   1     4
Honda Civic          30.4    4   75.7   52  4.93  1.615  18.52   1   1     4
Toyota Corolla       33.9    4   71.1   65  4.22  1.835  19.90   1   1     4
Toyota Corona        21.5    4  120.1   97  3.70  2.465  20.01   1   0     3
Dodge Challenger     15.5    8  318.0  150  2.76  3.520  16.87   0   0     3
AMC Javelin          15.2    8  304.0  150  3.15  3.435  17.30   0   0     3
Camaro Z28           13.3    8  350.0  245  3.73  3.840  15.41   0   0     3
Pontiac Firebird     19.2    8  400.0  175  3.08  3.845  17.05   0   0     3
Fiat X1-9            27.3    4   79.0   66  4.08  1.935  18.90   1   1     4
Porsche 914-2        26.0    4  120.3   91  4.43  2.140  16.70   0   1     5
Lotus Europa         30.4    4   95.1  113  3.77  1.513  16.90   1   1     5
Ford Pantera L       15.8    8  351.0  264  4.22  3.170  14.50   0   1     5
Ferrari Dino         19.7    6  145.0  175  3.62  2.770  15.50   0   1     5
Maserati Bora        15.0    8  301.0  335  3.54  3.570  14.60   0   1     5
Volvo 142E           21.4    4  121.0  109  4.11  2.780  18.60   1   1     4

                     carb             carmodel
rownames
Mazda RX4               4            Mazda RX4
Mazda RX4 Wag           4        Mazda RX4 Wag
Datsun 710              1           Datsun 710
Hornet 4 Drive          1       Hornet 4 Drive
Hornet Sportabout       2    Hornet Sportabout
Valiant                 1              Valiant
Duster 360              4           Duster 360
Merc 240D               2            Merc 240D
Merc 230                2             Merc 230
Merc 280                4             Merc 280
Merc 280C               4            Merc 280C
Merc 450SE              3           Merc 450SE
Merc 450SL              3           Merc 450SL
Merc 450SLC             3          Merc 450SLC
Cadillac Fleetwood      4   Cadillac Fleetwood
Lincoln Continental     4  Lincoln Continental
Chrysler Imperial       4    Chrysler Imperial
Fiat 128                1             Fiat 128
Honda Civic             2          Honda Civic
Toyota Corolla          1       Toyota Corolla
Toyota Corona           1        Toyota Corona
Dodge Challenger        2     Dodge Challenger
AMC Javelin             2          AMC Javelin
Camaro Z28              4           Camaro Z28
Pontiac Firebird        2     Pontiac Firebird
Fiat X1-9               1            Fiat X1-9
Porsche 914-2           2        Porsche 914-2
Lotus Europa            2         Lotus Europa
Ford Pantera L          4       Ford Pantera L
Ferrari Dino            6         Ferrari Dino
Maserati Bora           8        Maserati Bora
Volvo 142E              2           Volvo 142E

## Preview the Dataset

When you first open a new dataset in Python, tools like info(), head(), and describe() help you quickly understand what you’re working with.

- `df.info()` gives you a high-level overview of the dataset. It tells you how many rows and columns there are, the names of the columns, the data types (like numbers vs. text), and whether there are any missing values. You should look here to spot issues like unexpected data types or columns with lots of missing data.
- `df.head()` shows you the first few rows of the dataset. This lets you actually see what the data looks like—how values are formatted, what kind of information each column contains, and whether anything looks strange or inconsistent.
- `df.describe()` provides summary statistics for numerical columns, like the average, minimum, maximum, and quartiles. You should use this to get a sense of the range of values, typical values, and whether there might be outliers or unusual data points.

Together, these three tools give you a quick “first impression” of your dataset so you can start asking better questions and avoid mistakes early on.

In [3]:
#look at data types
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32 entries, Mazda RX4 to Volvo 142E
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   mpg       32 non-null     float64
 1   cyl       32 non-null     int64
 2   disp      32 non-null     float64
 3   hp        32 non-null     int64
 4   drat      32 non-null     float64
 5   wt        32 non-null     float64
 6   qsec      32 non-null     float64
 7   vs        32 non-null     int64
 8   am        32 non-null     int64
 9   gear      32 non-null     int64
 10  carb      32 non-null     int64
 11  carmodel  32 non-null     object
dtypes: float64(5), int64(6), object(1)
memory usage: 3.2+ KB

In [4]:
#look at top rows
df.head(10)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,carmodel
rownames,,,,,,,,,,,,
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,Mazda RX4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,Mazda RX4 Wag
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,Datsun 710
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,Hornet 4 Drive
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,Hornet Sportabout
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,Valiant
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,Duster 360
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,Merc 240D
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,Merc 230
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,Merc 280

In [5]:
#get a summary of the dataset
df.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

## Work with the Dataset

Learning the basic concepts of working with DataFrames in pandas gives you a powerful foundation for handling real-world data, which is a skill used in many careers—from business and finance to science, engineering, and tech. DataFrames make it easy to organize, clean, analyze, and visualize data in a structured way, similar to a spreadsheet but far more flexible and scalable. Some of the key tasks that Pandas allows are to:
- add or remove columns (variables)
- filter information
- compute summaries

Your goal is to learn to clean up data, visualize it, and use it to make business decisions using models.

### 🔧 Do the following: Task 1 - Work with DataFrame

🔧 Assignment Tasks - Practice selecting specific rows and columns.
- 1.1 Extract the mpg (miles per gallon) column and calculate its mean.
- 1.2 Create a new dataframe containing only the rows where mpg is greater than 25.
- 1.3 Create a new dataframe with rows with the number of cylinders (cyl) is 4.  Include only the columns mpg and hp.

In [6]:
mean_mpg = df['mpg'].mean()
print(f"Mean of mpg: {mean_mpg}")

Mean of mpg: 20.090625000000003

In [8]:
df_mpg_gt_25 = df[df['mpg'] > 25]
display(df_mpg_gt_25.head())

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,carmodel,power_to_weight_ratio
rownames,,,,,,,,,,,,,
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,Fiat 128,30.000000
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,Honda Civic,32.198142
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,Toyota Corolla,35.422343
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,Fiat X1-9,34.108527
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,Porsche 914-2,42.523364

In [11]:
df_cyl4_mpg_hp = df[df['cyl'] == 4][['mpg', 'hp']]
display(df_cyl4_mpg_hp.head())

              mpg  hp
rownames
Datsun 710   22.8  93
Merc 240D    24.4  62
Merc 230     22.8  95
Fiat 128     32.4  66
Honda Civic  30.4  52


### 🔧 Do the following - Task 2 - Introduce derived columns.
- 2.1 Create a new column power_to_weight_ratio as hp / wt (horsepower divided by weight).

In [7]:
df['power_to_weight_ratio'] = df['hp'] / df['wt']
display(df.head())

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,carmodel,power_to_weight_ratio
rownames,,,,,,,,,,,,,
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,Mazda RX4,41.984733
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,Mazda RX4 Wag,38.260870
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,Datsun 710,40.086207
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,Hornet 4 Drive,34.214619
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,Hornet Sportabout,50.872093

### 🔧 Do the following - Task 3 - Summarize data.
- 3.1 Group the data by the number of cylinders (cyl) and calculate the average mpg for each group.
- 3.2 Find the maximum horsepower (hp) for cars in each gear group.

In [18]:
avg_mpg_by_cyl = df.groupby('cyl')['mpg'].mean()
print("Average MPG by number of cylinders")
display(avg_mpg_by_cyl)

Average MPG by number of cylinders

cyl
4    26.663636
6    19.742857
8    15.100000
Name: mpg, dtype: float64

In [17]:
max_hp_by_gear = df.groupby('gear')['hp'].max()
print("Maximum Horsepower by gear group:")
display(max_hp_by_gear)

Maximum Horsepower by gear group:

gear
3    245
4    123
5    335
Name: hp, dtype: int64

### 🔧 Do the following - Task 4 - Sorting Data
- 4.1 Sort the dataframe by mpg in descending order.
- 4.2 Sort the dataframe first by cyl and then by hp.

In [19]:
df_sorted_mpg_desc = df.sort_values(by='mpg', ascending=False)
print("Dataframe sorted by MPG in descending order (first 5 rows):")
display(df_sorted_mpg_desc.head())

Dataframe sorted by MPG in descending order (first 5 rows):

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,carmodel,power_to_weight_ratio
rownames,,,,,,,,,,,,,
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,Toyota Corolla,35.422343
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,Fiat 128,30.000000
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,Lotus Europa,74.686054
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,Honda Civic,32.198142
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,Fiat X1-9,34.108527

In [20]:
df_sorted_cyl_hp = df.sort_values(by=['cyl', 'hp'])
print("Dataframe sorted by cylinder and then by horsepower")
display(df_sorted_cyl_hp.head(20))

Dataframe sorted by cylinder and then by horsepower

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,carmodel,power_to_weight_ratio
rownames,,,,,,,,,,,,,
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,Honda Civic,32.198142
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,Merc 240D,19.435737
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,Toyota Corolla,35.422343
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,Fiat 128,30.000000
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,Fiat X1-9,34.108527
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,Porsche 914-2,42.523364
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,Datsun 710,40.086207
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,Merc 230,30.158730
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,Toyota Corona,39.350913
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,Volvo 142E,39.208633
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,Lotus Europa,74.686054
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,Valiant,30.346821
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,Mazda RX4,41.984733
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,Mazda RX4 Wag,38.260870
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,Hornet 4 Drive,34.214619
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,Merc 280,35.755814
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,Merc 280C,35.755814
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,Ferrari Dino,63.176895
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,Dodge Challenger,42.613636
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,AMC Javelin,43.668122

## 🔧 Task 5: Reflection (100 words or less per question)

1. If you were using Excel to analyze the same dataset, what are some of the features you would have used to do the tasks in this lab?
2. What are 3 advantages of using a Python notebook, compared to Excel?

### ✍️ Your Response: 🔧
1.  In Excel, I would have had to create a new sheet everytime I wanted to explore dimensions of the dataset so that I can keep it neat and easy to follow. I also would have had to set up calculations manually.
2.In Python Notebook, I can see everything that I did before and so can everyone that I share it with. I can also have Gemini handy to assist. I can view everything in one continuous notebook.

## Export Your Notebook to Submit in Canvas
- In the top menu, go to File > Download, click "Download .ipynb". Save the file to your laptop.
- In the left side menu, click the Folder icon, then click the "Upload to Session Storage" icon, and select the above saved file to add it to Colab's temporary Virtual Machine (VM) that allows us to work on our files in Colab.
- Convert the file to HTML using the code below.  You may be asked to approve access to the files
- Find the output file under Files in the left side menu
- Download your HTML file (*lab_02_dataframe_intro.html*) as your completed lab, to be uploaded to Canvas

In [ ]:
!jupyter nbconvert --to html "IS4487_Shingi_lab_02_dataframe_intro.ipynb"

## Submit your assignment

- Make sure that all of your output is shown.  If you get the “unable to render code block” error, try refreshing the cache or downloading raw data to manually upload into Colab as a workaround.
- Upload your HTML file to Canvas
- Optionally, save your file in your own GitHub account for future use